apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{  .Chart.Name }}-selector"
      version: "current"
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
        version: "current"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-1
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: BROWSER_URL
            value: activator.ml
          - name: NOTE_SERVICE_URL
            value: https://notes.g5marketingcloud.com
          - name: GKE
            value: "true"
          - name: GA_PROPERTY
            value: "UA-115892674-18"
          - name: INCLUDE_G5_UPDATABLES
            value: "false"
          - name : INCLUDE_G5_AUTH
            value: "false"
          - name: DATABASE_MAX_CONNECTIONS
            value: "10"
          - name: DATABASE_MIN_CONNECTIONS
            value: "0"
          - name: DATABASE_IDLE
            value: "1000"
          - name: DATABASE_AQUIRE
            value: "1000"
          - name: DATABASE_EVICT
            value: "1000"
          - name: DATABASE_SSL
            value: "true"
          - name: G5_AUTH_ENDPOINT
            value: https://auth.g5search.com/oauth/authorize
          - name: G5_TOKEN_ENDPOINT
            value: https://auth.g5search.com/oauth/token
          - name: G5_AUTH_REDIRECT_URI
            value: https://activity.g5marketingcloud.com/g5_auth/users/auth/g5/callback
          - name: DATABASE_LOGGING
            value: "true"
          - name: G5_AUTH_ME_ENDPOINT
            value: https://auth.g5search.com/v1/me
          - name : G5_AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: annotation
                key: G5_AUTH_CLIENT_ID
          - name : G5_AUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: annotation
                key: G5_AUTH_CLIENT_SECRET
          - name : SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: annotation
                key: SESSION_SECRET
          - name : JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: annotation
                key: JWT_SECRET
          - name: DATABASE_CA
            valueFrom:
              secretKeyRef:
                name: annotation
                key: DATABASE_CA
          - name: DATABASE_CERT
            valueFrom:
              secretKeyRef:
                name: annotation
                key: DATABASE_CERT
          - name: DATABASE_KEY
            valueFrom:
              secretKeyRef:
                name: service-activator
                key: DATABASE_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: msr
                key: DATABASE_URL
          - name: SF_USERNAME
            valueFrom:
                secretKeyRef:
                  name: annotation
                  key: SF_USERNAME
          - name: SF_PASSWORD
            valueFrom:
              secretKeyRef:
                name: annotation
                key: SF_PASSWORD
          - name: SF_TOKEN
            valueFrom:
              secretKeyRef:
                name: annotation
                key: SF_TOKEN
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: annotation
                key: REDIS_URL
          - name: SLACK_FEEDBACK_URL
            valueFrom:
              secretKeyRef:
                name: annotation
                key: SLACK_FEEDBACK_URL
          - name: NOTE_SERVICE_USERNAME
            valueFrom:
              secretKeyRef:
                name: msr
                key: NOTE_SERVICE_USERNAME
          - name: NOTE_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msr
                key: NOTE_SERVICE_PASSWORD
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
        {{- if .Values.image.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.image.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.image.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.image.readinessProbe | indent 10 }}
        {{- end }}